# -*- coding: utf-8 -*-
"""Single source of the repository layout. Every script takes its folders from here.

    00_assets/      downloaded resources: datasets/ (captures, NM_DATASET_ROOT) and models/ (third-party code, weights)
    01_dataset/     generated data: session lists, session keys, model inputs, field-name maps
    02_preprocess/  preprocessing code          03_model/  training code (+ our own model code)
    04_analysis/    analysis code               99_documents/  documents and results/
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent

ASSETS = ROOT / "00_assets"
DATASETS = Path(os.environ.get("NM_DATASET_ROOT", ASSETS / "datasets"))   # <dataset dir>/01_pcap, 02_session, 03_..., 04_...
DATASET_TOOLS = ASSETS / "datasets" / "_tools"                            # arrange, label, and check the official captures
UPSTREAM = ASSETS / "models"                                              # 04_etbert 05_yatc 06_netmamba 07_trafficformer

DATASET = ROOT / "01_dataset"                                             # <ds>/00_filelist*, session_keys.csv, <variant>/<model>/
PREPROCESS = ROOT / "02_preprocess"
MODEL = ROOT / "03_model"
OWN_MODELS = MODEL / "own_models"                                         # 02_xgboost (1,205 features), 03_2dcnn
PARAM = MODEL / "param"                                                   # trained models and importances (large; not released)
ANALYSIS = ROOT / "04_analysis"

DOCS = ROOT / "99_documents"
RESULTS = DOCS / "results"
MODEL_RESULTS = RESULTS / "model_results"                                 # per model / dataset / experiment / variant / seed
RESULT_TABLES = RESULTS / "result_tables"
WRONG_LIST = RESULTS / "wrong_lists"                                      # per-session errors (regenerated by training)
DATASET_STATS = RESULTS / "dataset_stats"                                 # per-class counts before / after refinement
REFINEMENT_COUNTS = RESULTS / "refinement_counts"                         # sessions removed per rule and per class
ANALYSIS_OUT = RESULTS / "analysis"                                       # 01_target_signal ... 08_seed_stats
EMB_DIR = RESULTS / "embeddings"                                          # a3 embeddings (silhouette, t-SNE)
SHAP_TREE = RESULTS / "shap_tree"                                         # raw tree SHAP (regenerated)
SHAP_DL = RESULTS / "shap_dl"                                             # raw DL SHAP (regenerated)
